language: ruby
cache: bundler

rvm:
  - 2.2.3
before_script:
	- cp config/database.yml.travis config/database.yml.sample 
  - psql -c 'create database workshops_test;' -U postgres
  - bundle exec rake db:drop db:create db:schema:load


addons:
  postgresql: '9.3'

script: RAILS_ENV=test bundle exec rspec